# Generated by Django 3.2.4 on 2021-08-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='item',
            field=models.CharField(choices=[('2D', '2D'), ('etc', '그외'), ('people', '실존인물'), ('character', '캐릭터')], max_length=80),
        ),
    ]
