# Generated by Django 3.2.6 on 2021-08-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='item',
            field=models.CharField(choices=[('character', '캐릭터'), ('people', '실존인물'), ('2D', '2D'), ('etc', '그외')], max_length=80),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='profile_img',
            field=models.ImageField(blank=True, default='./static/기본이미지.jpg', null=True, upload_to='accounts/'),
        ),
    ]
