# Generated by Django 3.2 on 2021-08-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='item',
            field=models.CharField(choices=[('etc', '그외'), ('character', '캐릭터'), ('2D', '2D'), ('people', '실존인물')], max_length=80),
        ),
    ]
