# Generated by Django 3.2 on 2021-08-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_usermodel_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='item',
            field=models.CharField(choices=[('etc', '그외'), ('2D', '2D'), ('people', '실존인물'), ('character', '캐릭터')], max_length=80),
        ),
    ]
