# Generated by Django 3.2.4 on 2021-08-11 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='c_email',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='c_return_deposit',
        ),
    ]
