# Generated by Django 3.2.4 on 2021-08-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20210811_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='product_image',
            field=models.ImageField(blank=True, default='../static/daytoyear.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='semigoods',
            name='product_image',
            field=models.ImageField(blank=True, default='../static/daytoyear.jpg', null=True, upload_to='images/'),
        ),
    ]
