# Generated by Django 3.2 on 2021-08-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_goods_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='item',
            field=models.CharField(choices=[('etc', '그외'), ('people', '실존인물'), ('2D', '2D'), ('character', '캐릭터')], max_length=80),
        ),
        migrations.AlterField(
            model_name='goods',
            name='term_deposit',
            field=models.DateField(),
        ),
    ]
