# Generated by Django 3.2.4 on 2021-08-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_goods_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='item',
            field=models.CharField(choices=[('2D', '2D'), ('people', '실존인물'), ('character', '캐릭터'), ('etc', '그외')], max_length=80),
        ),
    ]
