# Generated by Django 3.2 on 2021-08-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20210811_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='item',
            field=models.CharField(choices=[('character', '캐릭터'), ('people', '실존인물'), ('2D', '2D'), ('etc', '그외')], max_length=80),
        ),
    ]
