# Generated by Django 3.2.4 on 2021-08-11 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_alter_goods_item'),
        ('goods', '0007_alter_goods_item'),
    ]

    operations = [
    ]
