# Generated by Django 3.2.4 on 2021-08-11 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_merge_0005_alter_goods_item_0007_alter_goods_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='writer',
        ),
        migrations.AddField(
            model_name='semigoods',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='item',
            field=models.CharField(choices=[('2D', '2D'), ('character', '캐릭터'), ('etc', '그외'), ('people', '실존인물')], max_length=80),
        ),
        migrations.AlterField(
            model_name='goods',
            name='product_image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='term_deposit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='semigoods',
            name='product_image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='semigoods',
            name='semi_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='semigoods',
            name='semi_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='semigoods',
            name='tag',
            field=models.CharField(default='그 외', max_length=80),
        ),
        migrations.CreateModel(
            name='SemiPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.semigoods')),
            ],
        ),
    ]
